import 'package:get/get.dart';

class AppTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": enUS,
      };
}

final Map<String, String> enUS = {
  'app_name': 'Ozone London',
  'sign_in': 'Sign In',
  'sign_up': 'Sign up',
  'lost_your_password': 'Lost your password?',
  'your_username_and_email': 'Your username or email',
  'username': 'Username or email',
  'password': 'Password',
  'forgot_password': 'Forgot your password?',
  'log_in': 'Log In',
  'please_enter_your_username_and_email': 'Please enter your username or email',
  'please_enter_your_password': 'Please enter your password',
  'dont_have_an_account_yet': "Don't have an account yet?",
  'for_free': "for free",
  'name': "Name",
  'user_name': "Username",
  'email': "Email",
  'please_enter_your_name': 'Please enter your name',
  'please_enter_your_user_name': 'Please enter your user password',
  'please_enter_your_email': 'Please enter your email',
  'already_have_an_account': 'Already have an account?',
  'yes_i_agree_with': 'Yes, I agree with',
  'privacy_policy': ' Privacy Policy ',
  'and_terms_of_use': 'and Terms of Use',
  'what_are_you_looking_for': 'What are you looking for?',
  'shop_by_category': 'Shop by Category',
  'this_weeks_highlights': 'This week’s highlights',
  'see_more': 'See More',
  'filter': 'Filter',
  'short_by': 'Short By',
  'cancel': 'Cancel',
  'reset': 'Reset',
  'apply': 'Apply',
  'categories': 'Categories',
  'brands': 'Brands',
  'price_range': 'Price range',
  'colors': 'Colors',
  'colors:': 'Colors: ',
  'size': 'Size: ',
  'add_to_cart': 'Add to cart',
  'product_detail': 'Product detail: ',
  'about_the_brand': 'About the brand: ',
  'rating_and_review': 'Rating & Review',
  'customer_review': 'Customer review',
  'helpful': 'Helpful',
  'username_or_email': 'Username or email',
  'reset_password': 'Reset password',
  'please_enter_your_username_or_email_address_you_will_receive_a_link_to_create_a_new_password_via_email':
      'Please enter your username or email address. You will receive a link to create a new password via email.',
  'edit_account': 'Edit Account',
  'orders': 'Orders',
  'sign_out': 'Sign out',
  'return': 'Return',
  'payment': 'Payment',
  'discount_coupon': "Discount Coupon",
  'my_account': 'My Account',
  'wishlist': 'Wishlist',
  'Orders': 'Orders',
  'save_cards': 'Save cards',
  'address': 'Address',
  'setting': 'Setting',
  'notification': 'Notification',
  'send_us_feedback': 'Send us feedback',
  'your_cart_is_empty': 'Your cart is currently empty',
  'you_may_check_out_all_the_available_products_and_buy_some_in_the_shop':
      'You may check out all the available products and buy some in the shop.',
  'continue_shopping': 'Continue Shopping',
  'saved_for_later': 'Saved for later',
  'user_create_successfully': 'User create successfully',
  'please_accept_the_privacy_policy_and_terms_of_use':
      'Please accept the Privacy Policy and Terms of Use',
  'validate_code': 'Validate code',
  'valid_code': 'Valid code',
  'please_enter_code': 'Please enter validate code',
  'confirm_password': 'Confirm password',
  'enter_your_new_password': 'Enter your new password',
  'please_enter_validate_code': 'Please enter validate code',
  'please_enter_confirm_password_as_same_as_new_password':
      'Please enter confirm password as same as new password',
  'please_enter_confirm_password': 'Please enter confirm password',
  'login_successfully': 'Login successfully',
  'total': 'Total',
  'secure_checkout': 'Secure checkout',
  'remove': 'Remove',
  'save_address': 'Save Address',
  'save_for_favourites': 'Save for favourites',
  'coupon_code': 'Coupon code',
  'coupon_code_applied_successfully': 'Coupon code applied successfully',
  'have_a_coupon_code': 'Have a coupon code?',
  'user_updated_successfully': 'User updated successfully',
  'write_review': 'Write a review',
  'you_rating': 'Your rating*: ',
  'what_did_you_like_or_dislike': 'What did you like or dislike?',
  'add_a_written_review': 'Add a written review',
  'please_select_a_rating': 'Please select a rating',
  'you_may_also_like': 'You may also like',
  'first_name': 'First name',
  'enter_your_first_name': 'Enter your first name',
  'please_enter_your_first_name': 'Please enter your first name',
  'last_name': 'Last name',
  'enter_your_last_name': 'Enter your last name',
  'please_enter_your_last_name': 'Please enter your last name',
  'display_name': 'Display name',
  'enter_your_display_name': 'Enter your display name',
  'please_enter_your_display_name': 'Please enter your display name',
  'this_will_be_how_your_name_will_be_displayed_in_the_account_section_and_in_reviews':
      'This will be how your name will be displayed in the account section and in reviews',
  'email_address': 'Email address',
  'enter_your_email': 'Enter your email',
  'please_enter_your_email_id': 'Please enter your email',
  'password_change': 'Password change',
  'current_password': 'Current password (leave blank to leave unchanged)',
  'enter_your_current_password': 'Enter your current password',
  'please_enter_your_current_password': 'Please enter your current password',
  'new_password': 'New password (leave blank to leave unchanged)',
  'please_enter_new_password': 'Please enter new password',
  'enter_confirm_password': 'Enter tour confirm password',
  'save_changes': 'Save changes',
  'wish_list': 'Wish list',
  'download': 'Download',
  'edit': 'Edit',
  'add_address': '+Add',
  'billing_address': 'Billing address',
  'company_name': 'Company name (optional)',
  'enter_your_company_name': 'Enter your company name',
  'country_region': 'Country / Region',
  'enter_your_country': 'Enter your country',
  'please_enter_your_country': 'Please enter your country',
  'street_address': 'Street address',
  'house_number_and_street_name': 'House number and street name',
  'please_enter_your_address': 'Please enter your address',
  'apartment_suits_unit': 'Apartment, suits, unit, ect. (optional)',
  'town_city': 'Town / City',
  'enter_your_town_city': 'Enter your town / city',
  'please_enter_your_town_city': 'Please enter your town / city',
  'state': 'State',
  'enter_your_state': 'Enter your state',
  'please_enter_your_state': 'Please enter your state',
  'pin_code': 'PIN Code',
  'enter_your_pin_code': 'Enter your pin code',
  'please_enter_your_pin_code': 'Please enter your pin code',
  'phone_number': 'Phone number',
  'enter_your_phone_number': 'Enter your phone number',
  'please_enter_your_phone_number': 'Please enter your phone number',
  'order_summary': 'Order Summary',
  'sub_total': 'Sub total',
  'discount': 'Discount',
  'shipping': 'Shipping',
  'checkout': 'Checkout',
  'ship_to': 'Ship to',
  'change_address': 'Change address',
  'credit_card_or_debit_card': 'Credit card or debit card',
  'cash_on_delivery': 'Cash On Delivery',
  'paypal': 'Paypal',
  'payment_method': 'Payment Method',
  'add': 'Add',
  'review_tour_order': 'Review your order',
  'no_data_found': 'No Data Found',
  'place_order': 'Place Order',
  'card_number': 'Card number',
  'cvv': 'CVV',
  'exp_date': 'Exp.Date',
  'card_holder_name': 'Card holder name',
  'confirm': 'Confirm',
  'promo_code': 'Promo code',
  'enter_promo_code': 'Enter promo code',
  'available_offers': 'Available offers',
  'added_to_your_cart': 'Added To Your Cart',
  'view_cart': 'View cart',
  'log_out?': 'Log Out?',
  'log_out': 'Log Out',
  'are_you_sure_want_to_logout': 'Are you sure want to logout?',
  'try_again': 'Try again',
  'network_error': 'Network Error',
  'network_error_description':
      'The connection to the network is impossible. Please check the status of you connection or try again in a few minutes',
  'order': 'Order:',
  'date': 'Date:',
  'status': 'Status:',
  'total:': 'Total:',
  'view': 'View',
  'order_detail': 'Order detail',
  'product:': 'Product:',
  'shipping:': 'Shipping:',
  'payment_method:': 'Payment method:',
  'gst:': 'GST:',
  'subtotal:': 'Sub Total:',
  'shipping_address': 'Shipping address',
  'product_list': 'Product List',
  'estimated_delivery': 'Estimated delivery:',
  'free_shipping_and_returns': 'Free Shipping & Returns',
  'ask_a_question': 'Ask a Question',
  'please_enter_your_message': 'Please enter your message',
  'your_message': 'Your message*',
  'submit_now': 'Submit Now',
  'question_and_answer': 'Question & Answer',
  'select_option': 'Select option',
  'note': 'Note',
  'add_note_for_seller': 'Add note for seller',
  'note_about_your_order':
      'Note about your order, e.g. special notes for delivery.',
  'save': 'Save',
};
