name: ozone_london
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5

  badges: ^3.1.1
  hidable: ^1.0.4
  share_plus: ^7.0.2
  get_storage: ^2.1.1
  flutter_svg: ^2.0.6
  like_button: ^2.0.5
  dynamic_size: ^0.1.5
  extended_image: ^8.0.2
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  country_picker: ^2.0.20
  flutter_offline: ^2.1.0
  pull_to_refresh: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_credit_card: ^3.0.6
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.4.0
  flutter_otp_text_field: ^1.1.1
  persistent_bottom_nav_bar: ^5.0.2
  flutter_stripe: ^9.2.2
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  pay: ^1.1.1
  ck_woocommerce_api:
    git: https://github.com/kishan-ck/ck_wooCommerce_api.git
  ck_wordpress_api:
    git:
      url: https://github.com/kishan-ck/ck_wordpress_api.git
      ref: main



dependency_overrides:
  http: ^1.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/font/jost/
    - assets/google_pay_payment_profile.json

  fonts:
    - family: Jost
      fonts:
        - asset: assets/font/jost/Jost-500-Medium.ttf
        - asset: assets/font/jost/Jost-700-Bold.ttf

